# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae6ef38bfb3fbd287afd07b0ae133ad79291e3fb94a6c1c08ef7589456bf5a24928788a5fc8748dc69ac894c499b4ecf6bcbef6f21ecaae8f7e1b020c2d75180

test:
  secret_key_base: 3cc322a55bb85cf472ca2437936b90c402e7dc1e1fc4b371a2696142fd7c98047a77d3d302434cb9ae841c32b2a5398fe9f2b100de6036e7fd048a2252c6b175

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
